import markdown from "@eslint/markdown";
import { defineConfig, globalIgnores } from "eslint/config";

export default defineConfig([
	// Generated by semantic-release on every release, so anything fixed here is
	// overwritten by the next one.
	globalIgnores(["CHANGELOG.md"]),
	{
		rules: {
			semi: "error",
			"prefer-const": "error",
		},
	},
	{
		files: ["**/*.md"],
		plugins: { markdown },
		language: "markdown/gfm",
		extends: ["markdown/recommended"],
	},
]);
